[packages]
# Available on both `Arch` and `Termux`
common = [
  "git",
  "gnupg",
  "openssh",
  "fish",
  "eza",
  "zoxide",
  "gopass",
  "starship",
  "fastfetch",
  "curl",
  "wget",
  "python",
]

[packages.android]
pkg = ["gh"]

[packages.arch]
yay = [
  # hyprland stuffs
  "uwsm",
  "hyprland",
  "hypridle",
  "hyprlock",
  "hyprpolkitagent",
  "hyprsunset",
  "hyprshot",
  "xdg-desktop-portal-hyprland",
  "xdg-desktop-portal-gtk",
  "qt5-wayland",
  "qt6-wyaland",
  "rofi-wayland",
  "dunst",
  "wayabr",
  "clipse",
  "brightnessctl",
  "qt6ct",
  "nwg-look",
  "swww",
  "matugen-bin",
  "bibata-cursor-git",
  "papirus-icon-theme",
  # Fonts
  "otf-codenewroman-nerd",
  "ttf-jetbrains-mono-nerd",
  # Must haves
  "docker",
  "docker-compose",
  "nautilus",
  "kitty",
  "neovide",
  "zen-browser-bin",
  "feh",
  # Drivers
  "intel-media-driver",
  "intel-ucode",
  # Dev
  "nodejs",
  "npm",
  "github-cli",
  "android-tools",
  # Misc
  "python-pipx",
  "stremio",
  "localsend-bin",
  "exercism-bin",
]
